name: Ockam Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-22.04
    environment: production
    concurrency:
      group: production
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Zone
        run: |
          curl -sSfL install.command.ockam.io | bash && source "$HOME/.ockam/env"
          ockam identity import "${{ secrets.OCKAM_IDENTITY }}"
          echo "${{ secrets.OCKAM_ZONE_SECRETS }}" > secrets.yaml
          ockam zone deploy
